name: Test / Default
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  github:
    name: GitHub runners
    strategy:
      fail-fast: false
      matrix:
        os: ${{ github.actor == 'dependabot[bot]' && fromJSON('["ubuntu-latest"]') || fromJSON('["ubuntu-latest", "windows-latest", "macos-latest"]') }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      # expectation: this is just a noop on managed runners
      - uses: ./
      - run: sleep 30